version: '3.8'

services:
  frontend:
    image: ghcr.io/laurec-24/mediu-raportare-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mediu-network

  backend:
    image: ghcr.io/laurec-24/mediu-raportare-backend:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres-db
      - DB_USER=mediu_user
      - DB_PASS=Pass1234MediU
      - DB_NAME=mediu_raportare_db
      - JWT_SECRET=c8f94a2b1d3e5f7a9c0b2d4e6f8a1c3b5d7e9f0a2c4b6d8e1f3a5c7b9d0e2f4a
      - PORT=5000
    depends_on:
      - postgres-db
    networks:
      - mediu-network

  postgres-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=mediu_user
      - POSTGRES_PASSWORD=Pass1234MediU
      - POSTGRES_DB=mediu_raportare_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
      - mediu-network

volumes:
  postgres_data_v2:

networks:
  mediu-network:
    driver: bridge
